### PR TITLE
Update RESULTS_GUIDELINES.md to require that footnotes are clearly visible.

### PR DESCRIPTION
**Pull request by DilipSequeira**
Add a requirement that footnotes be clearly visible.

### CODE REVIEW

**Comment by tjablin** [comment]
If we are at the point of legislating footnote size, there is clearly a problem. Do we really need rules for this?

**Comment by TheKanter** [comment]
Can we qualify by saying "in publications by submitters" or by members to scope it correctly?

**Comment by tjablin** [comment]
Can we resolve this pull request before the start of the next inference submission round?

**Comment by DilipSequeira** [comment]
updated in accordance with David's suggestion.

**Comment by johntran-nv** [comment]
The Training WG reviewed this on 3/10/22 and we approve this PR.

**Review by tjablin — APPROVED** [review]

**Comment by tjablin** [comment]
Inference WG: Approved.

**Comment by TheKanter** [comment]
I have begun the process of moving this language into the google doc and PDF.

**Comment by TheKanter** [comment]
This has been incorporated into the Google doc and approved by legal.

**Comment by TheKanter** [comment]
Hi Folks - first of all, my apologies for clobbering these changes with the switch to PDF. To make closing this issue easier, I want to point everyone to section IIIb here: https://drive.google.com/file/d/12qlUgwLSWYV0zTBWZSygc-Rj25DsL74R/view?usp=sharing

If @DilipSequeira wants to review the PDF and confirm this, we can close the issue.

**Comment by DilipSequeira** [comment]
Closing this - the reason it was never merged was that it intersected with moving the guidelines to google docs and back again. The guidelines now include text which covers the substance.

**Pull request closed without merging**
