### PR TITLE
Update rules schedule

### PR DESCRIPTION
**Pull request by TheKanter**
Final results on Thursday, not friday to support distribution to press.

### CODE REVIEW

**Review by rnaidu02 — COMMENTED** [review]
Since the results withdraw date is also moved to Thursday, I will bring this change to Inference WG notice and then approve on behalf of inference WG.

**Comment by rnaidu02** [comment]
No objections from Inference WG

**Comment by TheKanter** [comment]
Need to amend that results and press stuff shared with press on EOD Thursday before the results are released.

**Review by rnchukka — APPROVED** [review]

**Comment by rnchukka** [comment]
@guschmue merge this PR. I don't have write access.

**Pull request merged**
