### PR TITLE
Preview submission transitioning to Available

### PR DESCRIPTION
**Pull request by nv-rborkar**
Based on discussion in Training SWG on 02/10/2022, PR clarifies the criteria for evaluating equal-or-better performance of an available submission transitioning from preview.

### CODE REVIEW

**Comment by nv-rborkar** [comment]
The use of word _Comparable_ should eventually contain a hyperlink to the MLCommons website where benchmark comparability tables (or are they called "Compatability" tables?) are documented.

**Review by emizan76 — COMMENTED** [review]
Shall we write explicitly that a benchmark that is being retired when the available submission is made is NOT considered comparable?

**Comment by nv-rborkar** [comment]
Yes, I am open to defining what "Comparable" means. Ideally I wanted to include a hyperlink to the mlcommons website where the table displaying {comparable benchmarks x mlperf-rounds} will be hosted (the tables that @TheKanter shared two weeks back)

**Comment by nv-rborkar** [comment]
@petermattson to review & merge this PR.

**Review by petermattson — CHANGES_REQUESTED** [review]
Almost there! Suggest we add this sentence: "For an Available system that is larger than the preview system, absolute performance must be better. For an Available system that is smaller than the preview system, efficiency (time-to-train * number of chips) must be better." We need a clear definition to enable comparing across system scales.

**Comment by petermattson** [comment]
Hi Ritika,
Thanks for pushing this forward!
LGTM if you're OK with the added sentence I proposed.
Best,
Peter

**Comment by nv-rborkar** [comment]
Thanks Peter, I like the proposed text! 
Updated the PR and clarified the requirement for Inference separately.

We can circulate this across Inference SWG next.

**Comment by psyhtest** [comment]
>  A _Preview_ submission must include performance on at least one benchmark which will be considered _MLPerf Compatible_ (https://drive.google.com/file/d/1Dbz_jG4RMuB4Fugw_GWYV1gOw6P-MBpp/view) in the upcoming round where transition to _Available_ is made (consult SWG for Benchmark Roadmap).

Despite best intentions, it is not always known in advance if a benchmark is going to be _MLPerf Compatible_. For example, we are still debating whether SSD-MobileNet-v1 will be submittable in the next Inference round (v2.1). Therefore, a submitter who might have only submitted SSD-MobileNet-v1 in the previous round (v2.0) would be hot water.

**Comment by psyhtest** [comment]
By the way, when trying to access https://drive.google.com/file/d/1Dbz_jG4RMuB4Fugw_GWYV1gOw6P-MBpp/view, I get:

> No preview available. File is in owner's trash.

**Comment by nv-rborkar** [comment]
> Despite best intentions, it is not always known in advance if a benchmark is going to be MLPerf Compatible. For example, we are still debating whether SSD-MobileNet-v1 will be submittable in the next Inference round (v2.1). Therefore, a submitter who might have only submitted SSD-MobileNet-v1 in the previous round (v2.0) would be in hot water.

Good point @psyhtest. This could be a rare corner case and we can modify the PR to account for it with a provision such as:

`If none of the Preview benchmarks are MLPerf Compatible in the upcoming round where transition to Available is made, a submitter may get their performance validated in the upcoming round by making a submission on the old/retired benchmark to the Results WG during review period (such a submission will not show up on the Results table but will only be used by the Results WG to validate a past Preview Submission).
`

Training WG is trying to adhere to a [Benchmark Roadmap schedule](https://github.com/mlcommons/policies/blob/master/submission_rules.adoc#43-benchmark-roadmap-schedule) which requires the decision of carrying capacity & domain identification be made at least a round in advance (T-28 weeks or T-26 weeks is the deadline to make the decisions but the discussions should start even earlier) assuming rounds are 6 months or 24 weeks apart. 

I acknowledge Inference does not have a similar schedule (yet?).

The PR was written keeping the above schedule in mind with the intentions:

1.  A submitter should not misuse a **known** benchmark schedule to make a Preview submission and knowingly skip validation of performance when transitioning to Available
2.  A submitter or Results WG should not bear the burden of submitting or reviewing performance of a retired benchmark as long as there are other benchmarks submitted to validate a Preview submission's transition to Available

Do you agree with the spirit of the rule and the proposal to handle corner cases?

**Comment by nv-rborkar** [comment]
> By the way, when trying to access https://drive.google.com/file/d/1Dbz_jG4RMuB4Fugw_GWYV1gOw6P-MBpp/view, I get:

I fixed the link. Does this work now: https://drive.google.com/file/d/1vcb1yYkht6iQJsMLvTKrzBXgiZpwgKZ3/view?usp=sharing ?

Another way to access above is to click on `MLperf Compatibility Table`  here: https://mlcommons.org/en/policies/

**Comment by rnaidu02** [comment]
@nv-rborkar Could you update the compatibility table link (currently it is pointing to PDF) with the new github link ?

**Comment by rnaidu02** [comment]
Inference WG approved this PR.

**Comment by johntran-nv** [comment]
Training WG approves also, after the change from invalidating a submission to just the benchmark.

**Pull request merged**
