### PR TITLE
Update RESULTS_GUIDELINES.md

### PR DESCRIPTION
**Pull request by anirban-ghosh**
Proposing addition to results guidelines to cover guidelines for MLPerf power submissions.

### CODE REVIEW

**Comment by lizraymond** [comment]
apologies for delay -- this wording looks good to me and I much appreciate the expanded examples!

**Comment by tjablin** [comment]
Ping?

**Comment by lizraymond** [comment]
@tjablin looks ready for merge to me -- I don't have write access to this repo

**Review by s-idgunji — COMMENTED** [review]
@rnaidu02  -  Can you get this PR reviewed and committed in the Inference WG tomorrow.

**Comment by DilipSequeira** [comment]
I suggest we clarify by changing "Submitters are prohibited from making comparisons..." to "Submitters are prohibited from making any public comparisons..." 

This restricts the PR to what's enforceable.

**Comment by anirban-ghosh** [comment]
@DilipSequeira : Made the change.

**Comment by rnaidu02** [comment]
Inference WG approve this PG

**Pull request merged**
